#!/usr/bin/env python3

import sys
import datetime

license = open(f"{sys.argv[1]}/LICENSE", 'r').read().strip()

license_hdr = open(f"{sys.argv[2]}/License.h", 'w')

license_hdr.write( "/**\n")
license_hdr.write( " * @file License.h\n")
license_hdr.write( " *\n")
license_hdr.write(f" * @brief This file was autogenerated on {datetime.datetime.now()}\n")
license_hdr.write( " *        manual changes will not be tracked.\n")
license_hdr.write( " *\n")
license_hdr.write( " */\n\n")

license_hdr.write( "#ifndef LICENSE_H\n")
license_hdr.write( "# define LICENSE_H\n\n")

license_hdr.write( "# include <string_view>\n\n")

license_hdr.write( "namespace MapNormalizer {\n")
license_hdr.write(f"    std::string_view MAP_NORMALIZER_LICENSE = R\"(\n{license}\n)\";\n");
license_hdr.write( "}\n\n")
license_hdr.write( "#endif\n")

