#!/usr/bin/env python3

import sys
import datetime

version = open(f"{sys.argv[1]}/.config/version.txt", 'r').read().strip()

tools_version_hdr = open(f"{sys.argv[2]}/ToolsVersion.h", 'w')

tools_version_hdr.write( "/**\n")
tools_version_hdr.write( " * @file ToolsVersion.h\n")
tools_version_hdr.write( " *\n")
tools_version_hdr.write(f" * @brief This file was autogenerated on {datetime.datetime.now()}\n")
tools_version_hdr.write( " *        manual changes will not be tracked.\n")
tools_version_hdr.write( " *\n")
tools_version_hdr.write( " */\n\n")

tools_version_hdr.write( "#ifndef TOOLS_VERSION_H\n")
tools_version_hdr.write( "# define TOOLS_VERSION_H\n\n")
tools_version_hdr.write(f"# define MAP_NORMALIZER_VERSION \"{version}\"\n\n")
tools_version_hdr.write( "#endif\n")

